### ISSUE TITLE
pint 0.9 fails to import on python2.7 ImportError: No module named funcsigs

### ISSUE THREAD

**Issue by akrherz** [conda-forge/pint-feedstock#23]
Issue: fresh python=2.7 install of pint 0.9 fails to import

```
$ conda create -n py27 python=2.7 pint
Solving environment: done

## Package Plan ##

  environment location: /opt/miniconda3/envs/py27

  added / updated specs: 
    - pint
    - python=2.7


The following NEW packages will be INSTALLED:

    ca-certificates: 2018.11.29-ha4d7672_0 conda-forge
    certifi:         2018.11.29-py27_1000  conda-forge
    libffi:          3.2.1-hf484d3e_1005   conda-forge
    libgcc-ng:       7.3.0-hdf63c60_0      conda-forge
    libstdcxx-ng:    7.3.0-hdf63c60_0      conda-forge
    ncurses:         6.1-hf484d3e_1002     conda-forge
    openssl:         1.0.2p-h14c3975_1002  conda-forge
    pint:            0.9-py_0              conda-forge
    pip:             18.1-py27_1000        conda-forge
    python:          2.7.15-h938d71a_1006  conda-forge
    readline:        7.0-hf8c457e_1001     conda-forge
    setuptools:      40.6.3-py27_0         conda-forge
    sqlite:          3.26.0-h67949de_1000  conda-forge
    tk:              8.6.9-h84994c4_1000   conda-forge
    wheel:           0.32.3-py27_0         conda-forge
    zlib:            1.2.11-h14c3975_1004  conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
$ conda activate py27
$ python
>>> import pint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/py27/lib/python2.7/site-packages/pint/__init__.py", line 19, in <module>
    from .registry import (UnitRegistry, LazyRegistry)
  File "/opt/miniconda3/envs/py27/lib/python2.7/site-packages/pint/registry.py", line 48, in <module>
    from . import registry_helpers
  File "/opt/miniconda3/envs/py27/lib/python2.7/site-packages/pint/registry_helpers.py", line 22, in <module>
    from funcsigs import signature
ImportError: No module named funcsigs
```

 * using pint=0.8.1 works just fine.
 * installing `funcsigs` package allows pint=0.9 to work

**Comment by dopplershift** [comment]
So because this *was* suitable for noarch, the PR bumping it wasn't run against 2.7. *sigh* PR incoming...

**Comment by dopplershift** [comment]
Also, why in the world are you still running 2.7? 😉

**Comment by dopplershift** [comment]
should be good once packages rebuild

**Comment by akrherz** [comment]
> Also, why in the world are you still running 2.7?

Hehe, I am not, I just run my test suite against it on travis just to find exotic bugs to report!  Thanks for addressing this.
