### ISSUE TITLE
Missing importlib-resources for python < 3.7

### ISSUE THREAD

**Issue by bennybp** [conda-forge/pint-feedstock#41]
Issue:

Pint was updated to use `importlib_resources` for python < 3.7, but that is not pulled in via conda

https://github.com/hgrecco/pint/commit/2e75b734f189cfb81e5f650aeab684e4572053b0#diff-380c6a8ebbbce17d55d50ef17d3cf906

(Also, I find it interesting that importlib-metadata is pulled in twice somehow. See `conda list` below)

Output from a test import below:
```
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pint as pt
Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/condatest/lib/python3.6/site-packages/pint/registry.py", line 83, in <module>
    import importlib.resources as importlib_resources
ModuleNotFoundError: No module named 'importlib.resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ben/miniconda3/envs/condatest/lib/python3.6/site-packages/pint/__init__.py", line 29, in <module>
    from .registry import LazyRegistry, UnitRegistry
  File "/home/ben/miniconda3/envs/condatest/lib/python3.6/site-packages/pint/registry.py", line 86, in <module>
    import importlib_resources
ModuleNotFoundError: No module named 'importlib_resources'
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/ben/miniconda3/envs/condatest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py36h9f0ad1d_0    conda-forge
importlib-metadata        1.7.0            py36h9f0ad1d_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.2                  he6710b0_1  
openssl                   1.1.1g               h516909a_1    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pint                      0.16                       py_0    conda-forge
pip                       20.2.2                   py36_0  
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.6.12               hcff3b4d_2  
python_abi                3.6                     1_cp36m    conda-forge
readline                  8.0                  h7b6447c_0  
setuptools                49.6.0                   py36_0  
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
wheel                     0.35.1                     py_0  
xz                        5.2.5                h7b6447c_0  
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3 
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : condatest
    active env location : /home/ben/miniconda3/envs/condatest
            shell level : 2
       user config file : /home/ben/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.32
       base environment : /home/ben/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ben/miniconda3/pkgs
                          /home/ben/.conda/pkgs
       envs directories : /home/ben/miniconda3/envs
                          /home/ben/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/5.8.6-arch1-1 arch/ glibc/2.32
                UID:GID : 1000:985
             netrc file : /home/ben/.netrc
           offline mode : False

```
</details>

**Comment by dopplershift** [comment]
Fixed by #42. New packages are being built and should be available in about 30 minutes.
